# Generated by Django 5.2.1 on 2025-05-21 16:36

import taxi.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(
                help_text="Format: 3 uppercase letters followed by 5 digits.",
                max_length=8,
                unique=True,
                validators=["taxi.validators.validate_license_number"],
            ),
        ),
    ]
